# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/University/ML_DSA/vivado_proj/proj/user/ip/sha3_din_fifo/sha3_din_fifo.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sha3_din_fifo || ORIG_REF_NAME==sha3_din_fifo} -quiet] -quiet
