# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/ExpandA_sipo/ExpandA_sipo.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ExpandA_sipo || ORIG_REF_NAME==ExpandA_sipo} -quiet] -quiet
