# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/ExpandY_sipo/ExpandY_sipo.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ExpandY_sipo || ORIG_REF_NAME==ExpandY_sipo} -quiet] -quiet
