# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/University/ML_DSA/vivado_proj/proj/proj.srcs/sources_1/ip/hint_load_fifo/hint_load_fifo.xci
# IP: The module: 'hint_load_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/University/ML_DSA/vivado_proj/proj/proj.gen/sources_1/ip/hint_load_fifo/hint_load_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'hint_load_fifo'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/University/ML_DSA/vivado_proj/proj/proj.gen/sources_1/ip/hint_load_fifo/hint_load_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hint_load_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/University/ML_DSA/vivado_proj/proj/proj.srcs/sources_1/ip/hint_load_fifo/hint_load_fifo.xci
# IP: The module: 'hint_load_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/University/ML_DSA/vivado_proj/proj/proj.gen/sources_1/ip/hint_load_fifo/hint_load_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'hint_load_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/University/ML_DSA/vivado_proj/proj/proj.gen/sources_1/ip/hint_load_fifo/hint_load_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hint_load_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
