# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "D:/University/ML_DSA/vivado_proj/proj/.Xil/Vivado-15380-LAPTOP-EUGMKLPQ/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7a200tfbg484-2L
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    D:/University/ML_DSA/vivado_proj/proj/proj.srcs/sources_1/ip/ExpandS_sipo_1
    D:/University/ML_DSA/vivado_proj/proj/proj.srcs/sources_1/ip/ZetaRaw_ROM
  } {
      D:/University/ML_DSA/vivado_proj/proj/user/src/CoeffBlockRAM/RTL/CoeffBlockRAM.sv
      D:/University/ML_DSA/vivado_proj/proj/user/src/Polynomials/RTL/DSP_MultPipe.sv
      D:/University/ML_DSA/vivado_proj/proj/user/src/Sampler/RTL/ExpandA.sv
      D:/University/ML_DSA/vivado_proj/proj/user/src/Sampler/RTL/ExpandA_sipo96.sv
      D:/University/ML_DSA/vivado_proj/proj/user/src/Sampler/RTL/ExpandS.sv
      D:/University/ML_DSA/vivado_proj/proj/user/src/Polynomials/RTL/INTT_BU.sv
      D:/University/ML_DSA/vivado_proj/proj/user/src/CoeffBlockRAM/RTL/MatrixA.sv
      D:/University/ML_DSA/vivado_proj/proj/user/src/Polynomials/RTL/ModuleAdd.sv
      D:/University/ML_DSA/vivado_proj/proj/user/src/Polynomials/RTL/ModuleDiv2.sv
      D:/University/ML_DSA/vivado_proj/proj/user/src/Polynomials/RTL/ModuleMAC.sv
      D:/University/ML_DSA/vivado_proj/proj/user/src/Polynomials/RTL/ModuleMult.sv
      D:/University/ML_DSA/vivado_proj/proj/user/src/Polynomials/RTL/ModuleSub.sv
      D:/University/ML_DSA/vivado_proj/proj/user/src/Polynomials/RTL/NTT_BU.sv
      D:/University/ML_DSA/vivado_proj/proj/user/src/Polynomials/RTL/Poly_PAU.sv
      D:/University/ML_DSA/vivado_proj/proj/user/src/Polynomials/RTL/ReconfigCompute.sv
      D:/University/ML_DSA/vivado_proj/proj/user/src/Polynomials/RTL/ReconfigComputeUnit.sv
      D:/University/ML_DSA/vivado_proj/proj/user/src/CoeffBlockRAM/RTL/VectorS1.sv
      D:/University/ML_DSA/vivado_proj/proj/user/src/CoeffBlockRAM/RTL/VectorS2.sv
      D:/University/ML_DSA/vivado_proj/proj/user/src/CoeffBlockRAM/RTL/VectorT.sv
      D:/University/ML_DSA/vivado_proj/proj/user/src/CoeffBlockRAM/RTL/VectorY.sv
      D:/University/ML_DSA/vivado_proj/proj/user/src/Polynomials/RTL/ZetaRomAddrGen.sv
      D:/University/ML_DSA/vivado_proj/proj/user/src/CoeffBlockRAM/RTL/inferred_bram.sv
      D:/University/ML_DSA/vivado_proj/proj/user/src/keygen/RTL/keygen_internal.sv
    }
      rt::read_verilog -sv -include {
    D:/University/ML_DSA/vivado_proj/proj/proj.srcs/sources_1/ip/ExpandS_sipo_1
    D:/University/ML_DSA/vivado_proj/proj/proj.srcs/sources_1/ip/ZetaRaw_ROM
  } {
      D:/Xilinx_2021_1/Vivado/2021.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      D:/Xilinx_2021_1/Vivado/2021.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    D:/University/ML_DSA/vivado_proj/proj/proj.srcs/sources_1/ip/ExpandS_sipo_1
    D:/University/ML_DSA/vivado_proj/proj/proj.srcs/sources_1/ip/ZetaRaw_ROM
  } {
      D:/University/ML_DSA/vivado_proj/proj/.Xil/Vivado-15380-LAPTOP-EUGMKLPQ/realtime/ExpandA_sipo_stub.v
      D:/University/ML_DSA/vivado_proj/proj/.Xil/Vivado-15380-LAPTOP-EUGMKLPQ/realtime/ExpandS_sipo_1_stub.v
      D:/University/ML_DSA/vivado_proj/proj/.Xil/Vivado-15380-LAPTOP-EUGMKLPQ/realtime/ZetaRaw_ROM_stub.v
      D:/University/ML_DSA/vivado_proj/proj/user/src/param_conf.v
    }
      rt::read_vhdl -lib xpm D:/Xilinx_2021_1/Vivado/2021.1/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top keygen_internal
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "D:/University/ML_DSA/vivado_proj/proj/.Xil/Vivado-15380-LAPTOP-EUGMKLPQ/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
