# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/University/ML_DSA/vivado_proj/proj/proj.srcs/sources_1/ip/ExpandS_sipo_1/ExpandS_sipo_1.xci
# IP: The module: 'ExpandS_sipo_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/University/ML_DSA/vivado_proj/proj/proj.gen/sources_1/ip/ExpandS_sipo_1/ExpandS_sipo_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'ExpandS_sipo_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/University/ML_DSA/vivado_proj/proj/proj.gen/sources_1/ip/ExpandS_sipo_1/ExpandS_sipo_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ExpandS_sipo_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/University/ML_DSA/vivado_proj/proj/proj.srcs/sources_1/ip/ExpandS_sipo_1/ExpandS_sipo_1.xci
# IP: The module: 'ExpandS_sipo_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/University/ML_DSA/vivado_proj/proj/proj.gen/sources_1/ip/ExpandS_sipo_1/ExpandS_sipo_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'ExpandS_sipo_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/University/ML_DSA/vivado_proj/proj/proj.gen/sources_1/ip/ExpandS_sipo_1/ExpandS_sipo_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ExpandS_sipo_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
