# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/University/ML_DSA/vivado_proj/proj/proj.srcs/sources_1/ip/ExpandC_sipo/ExpandC_sipo.xci
# IP: The module: 'ExpandC_sipo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/University/ML_DSA/vivado_proj/proj/proj.gen/sources_1/ip/ExpandC_sipo/ExpandC_sipo.xdc
# XDC: The top module name and the constraint reference have the same name: 'ExpandC_sipo'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/University/ML_DSA/vivado_proj/proj/proj.gen/sources_1/ip/ExpandC_sipo/ExpandC_sipo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ExpandC_sipo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/University/ML_DSA/vivado_proj/proj/proj.srcs/sources_1/ip/ExpandC_sipo/ExpandC_sipo.xci
# IP: The module: 'ExpandC_sipo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/University/ML_DSA/vivado_proj/proj/proj.gen/sources_1/ip/ExpandC_sipo/ExpandC_sipo.xdc
# XDC: The top module name and the constraint reference have the same name: 'ExpandC_sipo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/University/ML_DSA/vivado_proj/proj/proj.gen/sources_1/ip/ExpandC_sipo/ExpandC_sipo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ExpandC_sipo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
